### ISSUE TITLE
Wait for page to load to scrape data

### ISSUE THREAD

**Issue by jayhuang75** [gocolly/colly#208]
Hello Everyone, 

I'm doing some POC now, I want to use the Go replace python to do the web scraping, and I found the awesome package. 
But one of the pages is using data binding and the data need a couple seconds to load. I just want to know is there any way we can like python (sleep couple seconds)?

Please advise. Thank you so much

**Comment by asciimoo** [comment]
Sleeping is possible, see the [time](https://golang.org/pkg/time/#example_Sleep) built-in package. However, I'm not sure if it will be enough to you, because Colly (and any other static scraper lib) doesn't execute the content of the page, so you have to extract manually the URL of the desired data and fetch it with Colly.
