### ISSUE TITLE
colly about the Success of Logon and cookie

### ISSUE THREAD

**Issue by chunfytseng** [gocolly/colly#384]
Question 1: When Gocolly logs in with Post, he only returns err. I want to get response. Because the err returned by user name or password is nil, I need to judge whether the login is successful according to the body or head returned. What should I do?

Question 2: how can gocolly set cookies and how can the specific code be implemented?

```
func Login(userName string, password string, c *colly.Collector) bool {
    err := c.Post(loginUrl, map[string]string{userName: password})
    // Whether the user name or password is correct or not, err is nil.
   //Why only return err, not response
    if err != nil {
        log.Fatal(err)
        return false
    }
    // if login isOK.will Get cookie
    return true
}

```

**Comment by vosmith** [comment]
Question 1:
In order to see the error, create an `ErrorCallback` function  and set it using `Collector.OnError()`.  This will give you access to the `Response` received from the server.

Question2:
Any cookie that is set by the server will be preserved by Colly.  If you want to add your own custom Cookie to send, use the `Collector.SetCookies()` method
