### ISSUE TITLE
How To stop the crawling process for some problematic website ?

### ISSUE THREAD

**Issue by yohaiaz** [gocolly/colly#427]
Hi all,
I need  to crawl websites and sometimes it is "bad designed  websites" with thousands (huge quantity) of links in a single page. I have a handler like that
c.OnHTML("a[href]", func(e *colly.HTMLElement){
//some logic here
})
I don't need to visit each link (html anchor tag with an href) in those pages so I don't call c.visit(url).

I want to limit my crawling logic to a max limit of links and after abort.
but calling e.Request.Abort() don't  really abort the colly crawling process. it continues for the web page in current process to call the handler func(e *colly.HTMLElement){} previously registered in c.OnHTML()

even using a counter and incrementing it atomically doesn't really help me for stopping this function to be called 

Any Idea of how to limit this ?

**Comment by asciimoo** [comment]
`e.Request.Abort` aborts only the current request which is already served if the OnHTML callback is called, so it doesn't have much effect at this time.
You can subscribe to the `body` tag instead of `a[href]` tags and manually iterate through the links with `e.ForEach` [0] or with `e.ForEachWithBreak` [1]. This way you can count how many links do you visit.

[0] https://pkg.go.dev/github.com/gocolly/colly/v2?tab=doc#HTMLElement.ForEach
[1] https://pkg.go.dev/github.com/gocolly/colly/v2?tab=doc#HTMLElement.ForEachWithBreak
