### ISSUE TITLE
Wildcard domains?

### ISSUE THREAD

**Issue by jimmypettersson** [gocolly/colly#544]
Hi!

Is there any way of specifying wildcard domains to `AllowedDomains()` such as `*.example.com` which automatically would allow `www.example.com` and `other.example.com`?

**Comment by jimmypettersson** [comment]
I guess you could achieve this functionality by using `DisallowedURLFilters()`, closing issue.

**Comment by v3470** [comment]
There is another problem if I try to use `DisallowedURLFilters` with `regexp`. Because golang's regex engine doesn't support negative look-ahead, I can not use "DisallowedURLFilters(`(?!\.google\.com`)" to make the same effect like "*.google.com" in whitelist. Is there any solution to achieve the wildcard domain allow?
