### ISSUE TITLE
Race condition due to incorrect sync.WaitGroup usage

### ISSUE THREAD

**Issue by THE108** [gocolly/colly#91]
Hi,

It seems that `sync.WaitGroup` is not used correctly in `func (c *Collector) scrape(...) error` method.

```
// colly.go:307
func (c *Collector) scrape(...) error {
    c.wg.Add(1)
    defer c.wg.Done()
    ...
```

Consider the following example (similar to http://go-colly.org/docs/examples/rate_limit/):
```
for _, url := range urls {
    go c.Visit(url)
}

c.Wait()
```

Here we call `Visit` (`scrape` wrapper) in a separate goroutine for each url and wait for their completion.

The problem is that it's not guaranteed that all goroutines will be finished after `c.Wait()` returns since "goroutine to wait" count is incremented inside each new goroutine - `c.wg.Add(1)`.

So, it's up to scheduler if `c.wg.Add(1)` will be called before or after `c.Wait()`.

I think there are two ways how that issue could be fixed:

1. Let caller handle `sync.WaitGroup`. Just provide a pointer to it as a param.
2. Provide an async API for `scrape` and it's wrappers.

Could look like that:
```
func (c *Collector) scrapeAsync(...) chan<- error {
    errChan := make(chan error)
    c.wg.Add(1)
    go func() {
        defer c.wg.Done()

        errChan <- c.scrape(...)
    }()
    return errChan
}
```

I can do a PR if you want.

**Comment by LeMoussel** [comment]
THE108 , why do you a `errChan  channel`?
Is it correct to do this?
`
    go func() {
        defer c.wg.Done()

        errChan := c.scrape(...)
        // Do some stuff ....

    }()

**Comment by THE108** [comment]
> Why do you a errChan channel?

I use it here to let caller wait for an error on that channel.

```
errChan := scrapeAsync(...)

... do stuff ...

err := <-errChan
```

> Is it correct to do this?

It depends on what are you going to do with that error (`c.scrape(...)` returns `error`).

**Comment by asciimoo** [comment]
@THE108 you are right, the current behavior is not suitable for your needs. As a workaround you can wrap `c.Visit` with a function and use a WaitGroup there.

The `func (c *Collector) scrapeAsync(...) chan<- error` approach is interesting, how do you imagine the public API for this? Duplicating all the `Visit`, `Post`, `PostRaw`, etc.. functions of the `Collector` and the `Request` with an `Async` prefix wouldn't be the best..
Perhaps `Collector` could be extended with an `Async bool` member and if `Collector.Async` is `true` then `scrapeAsync` would be called instead of `scrape`. With this solution it is not possible to return an error channel, this is the only downside, but errors can be handled in `OnError` callbacks. What do you think?

**Comment by THE108** [comment]
I think it's better to add new functionality than changing existing one (breaking back compatibility).

Anyway, I think both options are not perfect. So, maybe we can think about:

1. Let caller manage concurrency themselves. Just provide a `sync.WaitGroup` as a param (possibly `nil`).

2. Manage concurrency internally. `Collector` could handle its own goroutine pool  (which will provide better goroutine reuse and request rate limiting).

**Comment by asciimoo** [comment]
> I think it's better to add new functionality than changing existing one (breaking back compatibility).

The solution I suggested doesn't break the existing api.

**Comment by THE108** [comment]
Sorry, I misunderstood your suggestion.

> Perhaps Collector could be extended with an `Async bool` member and if `Collector.Async` is true then `scrapeAsync` would be called instead of `scrape`.

I think that should work.
